#!/usr/bin/env bash
#
# Bootstrap the AffiNE self-host + MCP stack on a fresh Linux machine.
# Idempotent: re-running keeps an existing .env and only fills in what's missing.
#
#   ./bootstrap.sh
#
set -euo pipefail
cd "$(dirname "$0")"

log()  { printf '\033[1;32m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m!  \033[0m %s\n' "$*"; }
die()  { printf '\033[1;31mERR\033[0m %s\n' "$*" >&2; exit 1; }

getenv() { grep -E "^$1=" .env 2>/dev/null | head -1 | cut -d= -f2-; }

# ---- 1. prerequisites ----
for bin in docker git openssl curl; do
  command -v "$bin" >/dev/null 2>&1 || die "missing required tool: $bin"
done
docker compose version >/dev/null 2>&1 || die "docker compose v2 is required"

# ---- 2. MCP submodule (pinned) ----
log "Initialising git submodule (affine-mcp-server)…"
git submodule update --init --recursive

# ---- 3. .env (secrets generated, account prompted) ----
if [ -f .env ]; then
  log ".env already exists — leaving it untouched."
else
  log "Creating .env (generating secrets)…"
  read -rp "AffiNE account email (you'll create this in the web UI): " ACC_EMAIL
  read -rsp "AffiNE account password: " ACC_PW; echo
  [ -n "$ACC_EMAIL" ] && [ -n "$ACC_PW" ] || die "email and password are required"

  DB_PASSWORD="$(openssl rand -hex 24)"
  MCP_TOKEN="$(openssl rand -hex 32)"

  cat > .env <<EOF
# Generated by bootstrap.sh — gitignored, do NOT commit.
PORT=3010
MCP_PORT=3011
UPLOAD_LOCATION=\${HOME}/.affine/self-host/storage
CONFIG_LOCATION=\${HOME}/.affine/self-host/config
DB_USERNAME=affine
DB_PASSWORD=${DB_PASSWORD}
DB_DATABASE=affine
AFFINE_MCP_HTTP_TOKEN=${MCP_TOKEN}
AFFINE_API_TOKEN=
AFFINE_EMAIL=${ACC_EMAIL}
AFFINE_PASSWORD=${ACC_PW}
AFFINE_TOOL_PROFILE=full
EOF
fi

PORT="$(getenv PORT)";       PORT="${PORT:-3010}"
MCP_PORT="$(getenv MCP_PORT)"; MCP_PORT="${MCP_PORT:-3011}"
MCP_TOKEN="$(getenv AFFINE_MCP_HTTP_TOKEN)"
ACC_EMAIL="$(getenv AFFINE_EMAIL)"

# ---- 4. data directories (uploads + config; Postgres uses a named volume) ----
log "Creating bind-mount directories under ${HOME}/.affine/self-host…"
mkdir -p "${HOME}/.affine/self-host/storage" \
         "${HOME}/.affine/self-host/config"

# ---- 5. MCP client config ----
log "Writing .mcp.json…"
sed -e "s|__MCP_PORT__|${MCP_PORT}|g" \
    -e "s|__AFFINE_MCP_HTTP_TOKEN__|${MCP_TOKEN}|g" \
    .mcp.json.example > .mcp.json

# ---- 6. start AffiNE and wait ----
log "Starting AffiNE (first run pulls images)…"
docker compose up -d affine

log "Waiting for AffiNE on http://localhost:${PORT} …"
until curl -fsS "http://localhost:${PORT}/graphql" \
        -H 'content-type: application/json' \
        -d '{"query":"{ serverConfig { version } }"}' >/dev/null 2>&1; do
  sleep 3
done
log "AffiNE is up."

# ---- 7. ensure the account exists ----
registered="$(curl -fsS "http://localhost:${PORT}/api/auth/preflight" \
  -H 'content-type: application/json' \
  -d "{\"email\":\"${ACC_EMAIL}\"}" 2>/dev/null || true)"
if ! printf '%s' "$registered" | grep -q '"registered":true'; then
  warn "Account '${ACC_EMAIL}' does not exist on this AffiNE yet."
  echo "    1. Open http://localhost:${PORT}"
  echo "    2. Sign up with that email + the password you entered"
  echo "    3. Create (or cloud-enable) a workspace so MCP can see it"
  read -rp "    Press Enter once the account is created… " _
fi

# ---- 8. start the MCP server ----
log "Building & starting the MCP server…"
docker compose up -d --build affine_mcp

echo
log "Done."
echo "    AffiNE web : http://localhost:${PORT}"
echo "    MCP (HTTP) : http://localhost:${MCP_PORT}/mcp  (Authorization: Bearer <token in .env>)"
echo "    Client cfg : ./.mcp.json"
